# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 671)
        MainWindow.setMinimumSize(QtCore.QSize(1105, 671))
        MainWindow.setMaximumSize(QtCore.QSize(1105, 671))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_geral = QtWidgets.QFrame(self.centralwidget)
        self.frame_geral.setGeometry(QtCore.QRect(0, 0, 1111, 691))
        self.frame_geral.setMinimumSize(QtCore.QSize(1111, 691))
        self.frame_geral.setMaximumSize(QtCore.QSize(1111, 691))
        self.frame_geral.setStyleSheet("QFrame{\n"
"color:white;\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit{\n"
"border: 1px solid white;\n"
"}")
        self.frame_geral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_geral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_geral.setObjectName("frame_geral")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_geral)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 258, 231, 201))
        self.stackedWidget.setStyleSheet("border: 0.5px solid gray;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_senoide = QtWidgets.QWidget()
        self.page_senoide.setObjectName("page_senoide")
        self.frame_senoide = QtWidgets.QFrame(self.page_senoide)
        self.frame_senoide.setEnabled(True)
        self.frame_senoide.setGeometry(QtCore.QRect(5, 5, 220, 190))
        self.frame_senoide.setStyleSheet("")
        self.frame_senoide.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_senoide.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_senoide.setObjectName("frame_senoide")
        self.label_3 = QtWidgets.QLabel(self.frame_senoide)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    border: 0px solid black;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_senoide)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    border: 0px solid black;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_senoide)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_5.setStyleSheet("QLabel{\n"
"    border: 0px solid black;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.lineEdit_periodica_amplitude = QtWidgets.QLineEdit(self.frame_senoide)
        self.lineEdit_periodica_amplitude.setEnabled(True)
        self.lineEdit_periodica_amplitude.setGeometry(QtCore.QRect(130, 30, 71, 21))
        self.lineEdit_periodica_amplitude.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_periodica_amplitude.setObjectName("lineEdit_periodica_amplitude")
        self.lineEdit_periodica_frequencia = QtWidgets.QLineEdit(self.frame_senoide)
        self.lineEdit_periodica_frequencia.setEnabled(True)
        self.lineEdit_periodica_frequencia.setGeometry(QtCore.QRect(130, 60, 71, 21))
        self.lineEdit_periodica_frequencia.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_periodica_frequencia.setObjectName("lineEdit_periodica_frequencia")
        self.lineEdit_periodica_offset = QtWidgets.QLineEdit(self.frame_senoide)
        self.lineEdit_periodica_offset.setEnabled(True)
        self.lineEdit_periodica_offset.setGeometry(QtCore.QRect(130, 90, 71, 21))
        self.lineEdit_periodica_offset.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_periodica_offset.setObjectName("lineEdit_periodica_offset")
        self.pushButton_periodica = QtWidgets.QPushButton(self.frame_senoide)
        self.pushButton_periodica.setGeometry(QtCore.QRect(70, 140, 75, 24))
        self.pushButton_periodica.setStyleSheet("QPushButton{\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;\n"
"}\n"
"QPushButton#pushButton_periodica:pressed {\n"
"    background-color: gray;\n"
"    color:white;\n"
"}")
        self.pushButton_periodica.setObjectName("pushButton_periodica")
        self.stackedWidget.addWidget(self.page_senoide)
        self.page_aleatoria = QtWidgets.QWidget()
        self.page_aleatoria.setObjectName("page_aleatoria")
        self.frame_aleatoria = QtWidgets.QFrame(self.page_aleatoria)
        self.frame_aleatoria.setGeometry(QtCore.QRect(5, 5, 220, 190))
        self.frame_aleatoria.setStyleSheet("QLabel{\n"
"    border: 0px solid gray;\n"
"}\n"
"\n"
".QPushButton{\n"
"color: white;\n"
"}\n"
".QPushButton:pressed {\n"
"    background-color: black;\n"
"    color:white;\n"
"}")
        self.frame_aleatoria.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_aleatoria.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_aleatoria.setObjectName("frame_aleatoria")
        self.label_6 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_6.setGeometry(QtCore.QRect(16, 22, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_aleatoria_AMax = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_AMax.setEnabled(True)
        self.lineEdit_aleatoria_AMax.setGeometry(QtCore.QRect(134, 20, 71, 21))
        self.lineEdit_aleatoria_AMax.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_aleatoria_AMax.setObjectName("lineEdit_aleatoria_AMax")
        self.label_7 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_7.setGeometry(QtCore.QRect(16, 54, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_aleatoria_AMin = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_AMin.setEnabled(True)
        self.lineEdit_aleatoria_AMin.setGeometry(QtCore.QRect(134, 53, 71, 21))
        self.lineEdit_aleatoria_AMin.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_aleatoria_AMin.setObjectName("lineEdit_aleatoria_AMin")
        self.lineEdit_aleatoria_PMax = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_PMax.setEnabled(True)
        self.lineEdit_aleatoria_PMax.setGeometry(QtCore.QRect(133, 85, 71, 21))
        self.lineEdit_aleatoria_PMax.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_aleatoria_PMax.setObjectName("lineEdit_aleatoria_PMax")
        self.label_8 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_8.setGeometry(QtCore.QRect(17, 87, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_aleatoria_PMin = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_PMin.setEnabled(True)
        self.lineEdit_aleatoria_PMin.setGeometry(QtCore.QRect(133, 117, 71, 21))
        self.lineEdit_aleatoria_PMin.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_aleatoria_PMin.setObjectName("lineEdit_aleatoria_PMin")
        self.label_9 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_9.setGeometry(QtCore.QRect(18, 120, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: 0px solid black;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_aleatoria = QtWidgets.QPushButton(self.frame_aleatoria)
        self.pushButton_aleatoria.setEnabled(True)
        self.pushButton_aleatoria.setGeometry(QtCore.QRect(71, 152, 75, 24))
        self.pushButton_aleatoria.setStyleSheet("QPushButton{\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;\n"
"}\n"
"QPushButton#pushButton_aleatoria:pressed {\n"
"    background-color: gray;\n"
"    color:white;\n"
"}")
        self.pushButton_aleatoria.setObjectName("pushButton_aleatoria")
        self.stackedWidget.addWidget(self.page_aleatoria)
        self.page_degrau = QtWidgets.QWidget()
        self.page_degrau.setObjectName("page_degrau")
        self.frame_degrau = QtWidgets.QFrame(self.page_degrau)
        self.frame_degrau.setGeometry(QtCore.QRect(5, 5, 220, 190))
        self.frame_degrau.setStyleSheet("")
        self.frame_degrau.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_degrau.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_degrau.setObjectName("frame_degrau")
        self.label_degrau_amplitude = QtWidgets.QLabel(self.frame_degrau)
        self.label_degrau_amplitude.setGeometry(QtCore.QRect(20, 70, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_degrau_amplitude.setFont(font)
        self.label_degrau_amplitude.setStyleSheet("QLabel{\n"
"    border: 0px solid black;\n"
"}")
        self.label_degrau_amplitude.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_degrau_amplitude.setObjectName("label_degrau_amplitude")
        self.lineEdit_degrau_amplitude = QtWidgets.QLineEdit(self.frame_degrau)
        self.lineEdit_degrau_amplitude.setGeometry(QtCore.QRect(110, 70, 81, 21))
        self.lineEdit_degrau_amplitude.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_degrau_amplitude.setObjectName("lineEdit_degrau_amplitude")
        self.pushButton_degrau = QtWidgets.QPushButton(self.frame_degrau)
        self.pushButton_degrau.setGeometry(QtCore.QRect(72, 120, 75, 24))
        self.pushButton_degrau.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#pushButton_degrau:pressed {\n"
"    background-color: gray;\n"
"    color:white;\n"
"}")
        self.pushButton_degrau.setObjectName("pushButton_degrau")
        self.stackedWidget.addWidget(self.page_degrau)
        self.frame = QtWidgets.QFrame(self.frame_geral)
        self.frame.setGeometry(QtCore.QRect(30, 20, 231, 71))
        self.frame.setStyleSheet("border: 1px solid gray;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(22, 10, 100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px solid black;")
        self.label.setObjectName("label")
        self.comboBox_malha = QtWidgets.QComboBox(self.frame)
        self.comboBox_malha.setGeometry(QtCore.QRect(130, 10, 91, 22))
        self.comboBox_malha.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 1px 3px 1px 3px;\n"
"}")
        self.comboBox_malha.setObjectName("comboBox_malha")
        self.comboBox_malha.addItem("")
        self.comboBox_malha.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(23, 40, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px solid black;")
        self.label_2.setObjectName("label_2")
        self.comboBox_onda = QtWidgets.QComboBox(self.frame)
        self.comboBox_onda.setGeometry(QtCore.QRect(130, 40, 91, 21))
        self.comboBox_onda.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 1px 3px 1px 3px;\n"
"}")
        self.comboBox_onda.setObjectName("comboBox_onda")
        self.comboBox_onda.addItem("")
        self.comboBox_onda.addItem("")
        self.comboBox_onda.addItem("")
        self.comboBox_onda.addItem("")
        self.comboBox_onda.addItem("")
        self.widget_ploter = QtWidgets.QWidget(self.frame_geral)
        self.widget_ploter.setGeometry(QtCore.QRect(290, 90, 781, 501))
        self.widget_ploter.setMinimumSize(QtCore.QSize(781, 501))
        self.widget_ploter.setMaximumSize(QtCore.QSize(781, 501))
        self.widget_ploter.setStyleSheet("border: 1px solid gray;")
        self.widget_ploter.setObjectName("widget_ploter")
        self.frame_checkboxes = QtWidgets.QFrame(self.frame_geral)
        self.frame_checkboxes.setGeometry(QtCore.QRect(290, 20, 781, 51))
        self.frame_checkboxes.setStyleSheet("border: 1px solid gray;\n"
"checkBox{\n"
"border: 0px solid gray;\n"
"}")
        self.frame_checkboxes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_checkboxes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_checkboxes.setObjectName("frame_checkboxes")
        self.checkBox_bloco1 = QtWidgets.QCheckBox(self.frame_checkboxes)
        self.checkBox_bloco1.setGeometry(QtCore.QRect(53, 19, 151, 20))
        self.checkBox_bloco1.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_bloco1.setChecked(True)
        self.checkBox_bloco1.setObjectName("checkBox_bloco1")
        self.checkBox_bloco2 = QtWidgets.QCheckBox(self.frame_checkboxes)
        self.checkBox_bloco2.setGeometry(QtCore.QRect(320, 16, 131, 20))
        self.checkBox_bloco2.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_bloco2.setChecked(True)
        self.checkBox_bloco2.setObjectName("checkBox_bloco2")
        self.checkBox_referencia = QtWidgets.QCheckBox(self.frame_checkboxes)
        self.checkBox_referencia.setGeometry(QtCore.QRect(620, 17, 111, 20))
        self.checkBox_referencia.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_referencia.setChecked(True)
        self.checkBox_referencia.setObjectName("checkBox_referencia")
        self.stackedWidget_controladores = QtWidgets.QStackedWidget(self.frame_geral)
        self.stackedWidget_controladores.setGeometry(QtCore.QRect(30, 471, 231, 133))
        self.stackedWidget_controladores.setStyleSheet("border: 1px solid gray;")
        self.stackedWidget_controladores.setObjectName("stackedWidget_controladores")
        self.page_P = QtWidgets.QWidget()
        self.page_P.setObjectName("page_P")
        self.frame_P = QtWidgets.QFrame(self.page_P)
        self.frame_P.setGeometry(QtCore.QRect(6, 5, 217, 121))
        self.frame_P.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_P.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_P.setObjectName("frame_P")
        self.label_10 = QtWidgets.QLabel(self.frame_P)
        self.label_10.setGeometry(QtCore.QRect(40, 56, 51, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_10.setStyleSheet("border: 0px solid gray;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_P = QtWidgets.QLineEdit(self.frame_P)
        self.lineEdit_P.setGeometry(QtCore.QRect(120, 52, 71, 25))
        self.lineEdit_P.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"};")
        self.lineEdit_P.setObjectName("lineEdit_P")
        self.stackedWidget_controladores.addWidget(self.page_P)
        self.page_PI = QtWidgets.QWidget()
        self.page_PI.setObjectName("page_PI")
        self.frame_PI = QtWidgets.QFrame(self.page_PI)
        self.frame_PI.setGeometry(QtCore.QRect(6, 5, 218, 121))
        self.frame_PI.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_PI.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_PI.setObjectName("frame_PI")
        self.label_12 = QtWidgets.QLabel(self.frame_PI)
        self.label_12.setGeometry(QtCore.QRect(27, 30, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: 0px solid gray;")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_pdpi = QtWidgets.QLabel(self.frame_PI)
        self.label_pdpi.setGeometry(QtCore.QRect(30, 62, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_pdpi.setFont(font)
        self.label_pdpi.setStyleSheet("border: 0px solid gray;")
        self.label_pdpi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_pdpi.setObjectName("label_pdpi")
        self.lineEdit_PIPD_kp = QtWidgets.QLineEdit(self.frame_PI)
        self.lineEdit_PIPD_kp.setGeometry(QtCore.QRect(120, 30, 71, 25))
        self.lineEdit_PIPD_kp.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"};")
        self.lineEdit_PIPD_kp.setObjectName("lineEdit_PIPD_kp")
        self.lineEdit_PIPD_ki = QtWidgets.QLineEdit(self.frame_PI)
        self.lineEdit_PIPD_ki.setGeometry(QtCore.QRect(120, 62, 71, 25))
        self.lineEdit_PIPD_ki.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.lineEdit_PIPD_ki.setObjectName("lineEdit_PIPD_ki")
        self.stackedWidget_controladores.addWidget(self.page_PI)
        self.page_PID = QtWidgets.QWidget()
        self.page_PID.setObjectName("page_PID")
        self.frame_PID_ganhos = QtWidgets.QFrame(self.page_PID)
        self.frame_PID_ganhos.setGeometry(QtCore.QRect(6, 5, 217, 121))
        self.frame_PID_ganhos.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_PID_ganhos.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_PID_ganhos.setObjectName("frame_PID_ganhos")
        self.lineEdit_PID_kp = QtWidgets.QLineEdit(self.frame_PID_ganhos)
        self.lineEdit_PID_kp.setGeometry(QtCore.QRect(110, 14, 71, 25))
        self.lineEdit_PID_kp.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"};")
        self.lineEdit_PID_kp.setObjectName("lineEdit_PID_kp")
        self.lineEdit_PID_ki = QtWidgets.QLineEdit(self.frame_PID_ganhos)
        self.lineEdit_PID_ki.setGeometry(QtCore.QRect(110, 52, 71, 25))
        self.lineEdit_PID_ki.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"};")
        self.lineEdit_PID_ki.setObjectName("lineEdit_PID_ki")
        self.lineEdit_PID_kd = QtWidgets.QLineEdit(self.frame_PID_ganhos)
        self.lineEdit_PID_kd.setGeometry(QtCore.QRect(110, 86, 71, 25))
        self.lineEdit_PID_kd.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"};")
        self.lineEdit_PID_kd.setObjectName("lineEdit_PID_kd")
        self.label_14 = QtWidgets.QLabel(self.frame_PID_ganhos)
        self.label_14.setGeometry(QtCore.QRect(50, 19, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border: 0px solid gray;")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_PID_ganhos)
        self.label_15.setGeometry(QtCore.QRect(50, 53, 31, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border: 0px solid gray;")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_PID_ganhos)
        self.label_16.setGeometry(QtCore.QRect(54, 90, 21, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: 0px solid gray;")
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.stackedWidget_controladores.addWidget(self.page_PID)
        self.frame_controle = QtWidgets.QFrame(self.frame_geral)
        self.frame_controle.setGeometry(QtCore.QRect(30, 106, 231, 81))
        self.frame_controle.setStyleSheet("border: 1px solid gray;")
        self.frame_controle.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_controle.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_controle.setObjectName("frame_controle")
        self.label_11 = QtWidgets.QLabel(self.frame_controle)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: 0px solid black;")
        self.label_11.setObjectName("label_11")
        self.comboBox_control = QtWidgets.QComboBox(self.frame_controle)
        self.comboBox_control.setGeometry(QtCore.QRect(128, 9, 91, 25))
        self.comboBox_control.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 1px 3px 1px 3px;\n"
"}")
        self.comboBox_control.setObjectName("comboBox_control")
        self.comboBox_control.addItem("")
        self.comboBox_control.addItem("")
        self.comboBox_control.addItem("")
        self.comboBox_control.addItem("")
        self.comboBox_control.addItem("")
        self.comboBox_control.addItem("")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_controle)
        self.checkBox_2.setGeometry(QtCore.QRect(60, 50, 111, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("border: 0px solid black;\n"
"color: white;\n"
"QCheckBox::indicator:checked {\n"
"    color:red\n"
"}")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_controle = QtWidgets.QPushButton(self.frame_geral)
        self.pushButton_controle.setGeometry(QtCore.QRect(83, 619, 121, 31))
        self.pushButton_controle.setStyleSheet("QPushButton{\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;\n"
"}\n"
"QPushButton#pushButton_controle:pressed {\n"
"    background-color: gray;\n"
"    color:white;\n"
"}")
        self.pushButton_controle.setObjectName("pushButton_controle")
        self.frame_saida = QtWidgets.QFrame(self.frame_geral)
        self.frame_saida.setGeometry(QtCore.QRect(30, 203, 231, 41))
        self.frame_saida.setStyleSheet("border: 1px solid gray;")
        self.frame_saida.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_saida.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_saida.setObjectName("frame_saida")
        self.comboBox_saida = QtWidgets.QComboBox(self.frame_saida)
        self.comboBox_saida.setGeometry(QtCore.QRect(125, 7, 91, 25))
        self.comboBox_saida.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.comboBox_saida.setAutoFillBackground(False)
        self.comboBox_saida.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 1px 3px 1px 3px;\n"
"}")
        self.comboBox_saida.setObjectName("comboBox_saida")
        self.comboBox_saida.addItem("")
        self.comboBox_saida.addItem("")
        self.label_13 = QtWidgets.QLabel(self.frame_saida)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border: 0px solid black;")
        self.label_13.setObjectName("label_13")
        self.frame_checkboxes_erros = QtWidgets.QFrame(self.frame_geral)
        self.frame_checkboxes_erros.setGeometry(QtCore.QRect(290, 607, 781, 41))
        self.frame_checkboxes_erros.setStyleSheet("border: 1px solid gray;\n"
"checkBox{\n"
"border: 0px solid gray;\n"
"}")
        self.frame_checkboxes_erros.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_checkboxes_erros.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_checkboxes_erros.setObjectName("frame_checkboxes_erros")
        self.checkBox_errorProp = QtWidgets.QCheckBox(self.frame_checkboxes_erros)
        self.checkBox_errorProp.setGeometry(QtCore.QRect(180, 10, 151, 20))
        self.checkBox_errorProp.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_errorProp.setChecked(True)
        self.checkBox_errorProp.setObjectName("checkBox_errorProp")
        self.checkBox_errorDeriv = QtWidgets.QCheckBox(self.frame_checkboxes_erros)
        self.checkBox_errorDeriv.setGeometry(QtCore.QRect(400, 10, 131, 20))
        self.checkBox_errorDeriv.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_errorDeriv.setChecked(True)
        self.checkBox_errorDeriv.setObjectName("checkBox_errorDeriv")
        self.checkBox_errorInteg = QtWidgets.QCheckBox(self.frame_checkboxes_erros)
        self.checkBox_errorInteg.setGeometry(QtCore.QRect(600, 10, 111, 20))
        self.checkBox_errorInteg.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_errorInteg.setChecked(True)
        self.checkBox_errorInteg.setObjectName("checkBox_errorInteg")
        self.checkBox_errorGeral = QtWidgets.QCheckBox(self.frame_checkboxes_erros)
        self.checkBox_errorGeral.setGeometry(QtCore.QRect(20, 10, 111, 20))
        self.checkBox_errorGeral.setStyleSheet("color: white;\n"
"border: 0px solid gray;")
        self.checkBox_errorGeral.setChecked(True)
        self.checkBox_errorGeral.setObjectName("checkBox_errorGeral")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_controladores.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Monitoramento"))
        self.label_3.setText(_translate("MainWindow", "Amplitude"))
        self.label_4.setText(_translate("MainWindow", "Frequencia"))
        self.label_5.setText(_translate("MainWindow", "Offset"))
        self.pushButton_periodica.setText(_translate("MainWindow", "OK"))
        self.label_6.setText(_translate("MainWindow", "Amplitude Max"))
        self.label_7.setText(_translate("MainWindow", "Amplitude Min"))
        self.label_8.setText(_translate("MainWindow", "Periodo Max"))
        self.label_9.setText(_translate("MainWindow", "Periodo Min"))
        self.pushButton_aleatoria.setText(_translate("MainWindow", "OK"))
        self.label_degrau_amplitude.setText(_translate("MainWindow", "Amplitude"))
        self.pushButton_degrau.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "Tipo de Malha"))
        self.comboBox_malha.setItemText(0, _translate("MainWindow", "Aberta"))
        self.comboBox_malha.setItemText(1, _translate("MainWindow", "Fechada"))
        self.label_2.setText(_translate("MainWindow", "Tipo de Onda"))
        self.comboBox_onda.setItemText(0, _translate("MainWindow", "Senoide"))
        self.comboBox_onda.setItemText(1, _translate("MainWindow", "Degrau"))
        self.comboBox_onda.setItemText(2, _translate("MainWindow", "Quadrada"))
        self.comboBox_onda.setItemText(3, _translate("MainWindow", "Serra"))
        self.comboBox_onda.setItemText(4, _translate("MainWindow", "Aleatoria"))
        self.checkBox_bloco1.setText(_translate("MainWindow", "Saida 1 (Vermelha)"))
        self.checkBox_bloco2.setText(_translate("MainWindow", "Saida 2 (Verde)"))
        self.checkBox_referencia.setText(_translate("MainWindow", "Referência"))
        self.label_10.setText(_translate("MainWindow", "Kp"))
        self.label_12.setText(_translate("MainWindow", "Kp"))
        self.label_pdpi.setText(_translate("MainWindow", "Ki"))
        self.label_14.setText(_translate("MainWindow", "Kp"))
        self.label_15.setText(_translate("MainWindow", "Ki"))
        self.label_16.setText(_translate("MainWindow", "Kd"))
        self.label_11.setText(_translate("MainWindow", "Controlador"))
        self.comboBox_control.setItemText(0, _translate("MainWindow", "P"))
        self.comboBox_control.setItemText(1, _translate("MainWindow", "PD"))
        self.comboBox_control.setItemText(2, _translate("MainWindow", "PI"))
        self.comboBox_control.setItemText(3, _translate("MainWindow", "PID"))
        self.comboBox_control.setItemText(4, _translate("MainWindow", "PI-D"))
        self.comboBox_control.setItemText(5, _translate("MainWindow", "I-PD"))
        self.checkBox_2.setText(_translate("MainWindow", "Usar Ganhos"))
        self.pushButton_controle.setText(_translate("MainWindow", "Aplicar Controle"))
        self.comboBox_saida.setItemText(0, _translate("MainWindow", "Verde"))
        self.comboBox_saida.setItemText(1, _translate("MainWindow", "Vermelho"))
        self.label_13.setText(_translate("MainWindow", "Bloco Saida"))
        self.checkBox_errorProp.setText(_translate("MainWindow", "Erro Proporcional"))
        self.checkBox_errorDeriv.setText(_translate("MainWindow", "Erro Derivativo"))
        self.checkBox_errorInteg.setText(_translate("MainWindow", "Erro Integral"))
        self.checkBox_errorGeral.setText(_translate("MainWindow", "Error Geral"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
