# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_geral = QtWidgets.QFrame(self.centralwidget)
        self.frame_geral.setGeometry(QtCore.QRect(-1, -1, 991, 601))
        self.frame_geral.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_geral.setStyleSheet(
            "QFrame{\n"
            "color:white;\n"
            "    background-color: rgb(0, 0, 0);\n"
            "}\n"
            "QLineEdit{\n"
            "border: 1px solid white;\n"
            "}"
        )
        self.frame_geral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_geral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_geral.setObjectName("frame_geral")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_geral)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 279, 201, 201))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_senoide = QtWidgets.QWidget()
        self.page_senoide.setObjectName("page_senoide")
        self.frame_senoide = QtWidgets.QFrame(self.page_senoide)
        self.frame_senoide.setEnabled(True)
        self.frame_senoide.setGeometry(QtCore.QRect(-1, -1, 201, 201))
        self.frame_senoide.setStyleSheet("")
        self.frame_senoide.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_senoide.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_senoide.setObjectName("frame_senoide")
        self.label_3 = QtWidgets.QLabel(self.frame_senoide)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n" "    border: 0px solid black;\n" "}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_senoide)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n" "    border: 0px solid black;\n" "}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_senoide)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 49, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_5.setStyleSheet("QLabel{\n" "    border: 0px solid black;\n" "}")
        self.label_5.setObjectName("label_5")
        self.lineEdit_degrau_amplitude_2 = QtWidgets.QLineEdit(self.frame_senoide)
        self.lineEdit_degrau_amplitude_2.setEnabled(True)
        self.lineEdit_degrau_amplitude_2.setGeometry(QtCore.QRect(100, 30, 71, 21))
        self.lineEdit_degrau_amplitude_2.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_degrau_amplitude_2.setObjectName("lineEdit_degrau_amplitude_2")
        self.lineEdit_degrau_amplitude_3 = QtWidgets.QLineEdit(self.frame_senoide)
        self.lineEdit_degrau_amplitude_3.setEnabled(True)
        self.lineEdit_degrau_amplitude_3.setGeometry(QtCore.QRect(100, 60, 71, 21))
        self.lineEdit_degrau_amplitude_3.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_degrau_amplitude_3.setObjectName("lineEdit_degrau_amplitude_3")
        self.lineEdit_degrau_amplitude_4 = QtWidgets.QLineEdit(self.frame_senoide)
        self.lineEdit_degrau_amplitude_4.setEnabled(True)
        self.lineEdit_degrau_amplitude_4.setGeometry(QtCore.QRect(100, 90, 71, 21))
        self.lineEdit_degrau_amplitude_4.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_degrau_amplitude_4.setObjectName("lineEdit_degrau_amplitude_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_senoide)
        self.pushButton.setGeometry(QtCore.QRect(60, 130, 75, 24))
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "border: 1px solid gray;\n"
            "border-radius: 5px;\n"
            "color: white;\n"
            "}\n"
            "QPushButton#pushButton:pressed {\n"
            "    background-color: gray;\n"
            "    color:white;\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_senoide)
        self.page_aleatoria = QtWidgets.QWidget()
        self.page_aleatoria.setObjectName("page_aleatoria")
        self.frame_aleatoria = QtWidgets.QFrame(self.page_aleatoria)
        self.frame_aleatoria.setGeometry(QtCore.QRect(0, -1, 201, 201))
        self.frame_aleatoria.setStyleSheet(
            "QLabel{\n"
            "    border: 0px solid gray;\n"
            "}\n"
            "\n"
            ".QPushButton{\n"
            "color: white;\n"
            "}\n"
            ".QPushButton:pressed {\n"
            "    background-color: black;\n"
            "    color:white;\n"
            "}"
        )
        self.frame_aleatoria.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_aleatoria.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_aleatoria.setObjectName("frame_aleatoria")
        self.label_6 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_6.setGeometry(QtCore.QRect(13, 22, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_aleatoria_AMax = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_AMax.setEnabled(True)
        self.lineEdit_aleatoria_AMax.setGeometry(QtCore.QRect(109, 20, 71, 21))
        self.lineEdit_aleatoria_AMax.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_aleatoria_AMax.setObjectName("lineEdit_aleatoria_AMax")
        self.label_7 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_7.setGeometry(QtCore.QRect(13, 54, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_aleatoria_AMin = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_AMin.setEnabled(True)
        self.lineEdit_aleatoria_AMin.setGeometry(QtCore.QRect(110, 53, 71, 21))
        self.lineEdit_aleatoria_AMin.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_aleatoria_AMin.setObjectName("lineEdit_aleatoria_AMin")
        self.lineEdit_aleatoria_PMax = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_PMax.setEnabled(True)
        self.lineEdit_aleatoria_PMax.setGeometry(QtCore.QRect(109, 85, 71, 21))
        self.lineEdit_aleatoria_PMax.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_aleatoria_PMax.setObjectName("lineEdit_aleatoria_PMax")
        self.label_8 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_8.setGeometry(QtCore.QRect(13, 87, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_aleatoria_PMin = QtWidgets.QLineEdit(self.frame_aleatoria)
        self.lineEdit_aleatoria_PMin.setEnabled(True)
        self.lineEdit_aleatoria_PMin.setGeometry(QtCore.QRect(109, 117, 71, 21))
        self.lineEdit_aleatoria_PMin.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_aleatoria_PMin.setObjectName("lineEdit_aleatoria_PMin")
        self.label_9 = QtWidgets.QLabel(self.frame_aleatoria)
        self.label_9.setGeometry(QtCore.QRect(13, 119, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: 0px solid black;")
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_aleatoria)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 150, 75, 24))
        self.pushButton_3.setStyleSheet(
            "QPushButton{\n"
            "border: 1px solid gray;\n"
            "border-radius: 5px;\n"
            "}\n"
            "QPushButton#pushButton_3:pressed {\n"
            "    background-color: gray;\n"
            "    color:white;\n"
            "}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_aleatoria)
        self.page_degrau = QtWidgets.QWidget()
        self.page_degrau.setObjectName("page_degrau")
        self.frame_degrau = QtWidgets.QFrame(self.page_degrau)
        self.frame_degrau.setGeometry(QtCore.QRect(0, 0, 201, 201))
        self.frame_degrau.setStyleSheet("")
        self.frame_degrau.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_degrau.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_degrau.setObjectName("frame_degrau")
        self.label_degrau_amplitude = QtWidgets.QLabel(self.frame_degrau)
        self.label_degrau_amplitude.setGeometry(QtCore.QRect(10, 70, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_degrau_amplitude.setFont(font)
        self.label_degrau_amplitude.setStyleSheet(
            "QLabel{\n" "    border: 0px solid black;\n" "}"
        )
        self.label_degrau_amplitude.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_degrau_amplitude.setObjectName("label_degrau_amplitude")
        self.lineEdit_degrau_amplitude = QtWidgets.QLineEdit(self.frame_degrau)
        self.lineEdit_degrau_amplitude.setGeometry(QtCore.QRect(90, 70, 81, 21))
        self.lineEdit_degrau_amplitude.setStyleSheet(
            "QLineEdit{\n" "border: 1px solid black;\n" "border-radius: 5px;\n" "}"
        )
        self.lineEdit_degrau_amplitude.setObjectName("lineEdit_degrau_amplitude")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_degrau)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 120, 75, 24))
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "color:white;\n"
            "border: 1px solid gray;\n"
            "border-radius: 5px;\n"
            "}\n"
            "QPushButton#pushButton_2:pressed {\n"
            "    background-color: gray;\n"
            "    color:white;\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_degrau)
        self.frame = QtWidgets.QFrame(self.frame_geral)
        self.frame.setGeometry(QtCore.QRect(20, 120, 201, 91))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px solid black;")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(100, 20, 91, 22))
        self.comboBox.setStyleSheet(
            "QComboBox {\n"
            "    border: 1px solid gray;\n"
            "    border-radius: 5px;\n"
            "    padding: 1px 3px 1px 3px;\n"
            "}"
        )
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px solid black;")
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 50, 91, 21))
        self.comboBox_2.setStyleSheet(
            "QComboBox {\n"
            "    border: 1px solid gray;\n"
            "    border-radius: 5px;\n"
            "    padding: 1px 3px 1px 3px;\n"
            "}"
        )
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.widget_ploter = QtWidgets.QWidget(self.frame_geral)
        self.widget_ploter.setGeometry(QtCore.QRect(250, 70, 711, 451))
        self.widget_ploter.setStyleSheet("border: 1px solid gray;")
        self.widget_ploter.setObjectName("widget_ploter")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_geral)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 20, 75, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(
            "QPushButton{\n"
            "color: white;\n"
            "border: 1px solid gray;\n"
            "border-radius: 5px;\n"
            "}\n"
            "QPushButton#pushButton_4:pressed {\n"
            "    background-color: gray;\n"
            "    color:white;\n"
            "}"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Amplitude"))
        self.label_4.setText(_translate("MainWindow", "Frequencia"))
        self.label_5.setText(_translate("MainWindow", "Offset"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.label_6.setText(_translate("MainWindow", "Amplitude Max"))
        self.label_7.setText(_translate("MainWindow", "Amplitude Min"))
        self.label_8.setText(_translate("MainWindow", "Amplitude Max"))
        self.label_9.setText(_translate("MainWindow", "Amplitude Max"))
        self.pushButton_3.setText(_translate("MainWindow", "OK"))
        self.label_degrau_amplitude.setText(_translate("MainWindow", "Amplitude"))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "Tipo de Malha"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Aberta"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Fechada"))
        self.label_2.setText(_translate("MainWindow", "Tipo de Onda"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Senoide"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Degrau"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Quadrada"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Serra"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Aleatoria"))
        self.pushButton_4.setText(_translate("MainWindow", "Start"))

