# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/PrimaryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrimaryWindow(object):
    def setupUi(self, PrimaryWindow):
        PrimaryWindow.setObjectName("PrimaryWindow")
        PrimaryWindow.resize(685, 416)
        PrimaryWindow.setMinimumSize(QtCore.QSize(685, 416))
        PrimaryWindow.setMaximumSize(QtCore.QSize(685, 416))
        self.centralwidget = QtWidgets.QWidget(PrimaryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 131, 421))
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(131, 601))
        self.frame.setStyleSheet("background-color: rgb(156, 204, 152);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_white = QtWidgets.QFrame(self.centralwidget)
        self.frame_white.setGeometry(QtCore.QRect(120, 0, 571, 421))
        self.frame_white.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_white.setMaximumSize(QtCore.QSize(571, 421))
        self.frame_white.setStyleSheet("background-color: rgb(250, 245, 245);")
        self.frame_white.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_white.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_white.setObjectName("frame_white")
        self.label = QtWidgets.QLabel(self.frame_white)
        self.label.setGeometry(QtCore.QRect(130, 50, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_white)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 150, 404, 135))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(24, 22, 66, 19)
        self.formLayout.setHorizontalSpacing(51)
        self.formLayout.setVerticalSpacing(32)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: gray;\n"
"border: 2px solid gray;\n"
"border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"};")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"selection-background-color: gray;\n"
"border: 2px solid gray;\n"
"border-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"};")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_white)
        self.pushButton.setGeometry(QtCore.QRect(220, 330, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton:pressed {\n"
"    background-color: gray;\n"
"    color:white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        PrimaryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PrimaryWindow)
        QtCore.QMetaObject.connectSlotsByName(PrimaryWindow)

    def retranslateUi(self, PrimaryWindow):
        _translate = QtCore.QCoreApplication.translate
        PrimaryWindow.setWindowTitle(_translate("PrimaryWindow", "MainWindow"))
        self.label.setText(_translate("PrimaryWindow", "Configurações Iniciais"))
        self.label_2.setText(_translate("PrimaryWindow", "Tipo de Malha"))
        self.label_3.setText(_translate("PrimaryWindow", "Tipo de  Sinal"))
        self.comboBox.setItemText(0, _translate("PrimaryWindow", "Aberta"))
        self.comboBox.setItemText(1, _translate("PrimaryWindow", "Fechada"))
        self.comboBox_2.setItemText(0, _translate("PrimaryWindow", "Senoide"))
        self.comboBox_2.setItemText(1, _translate("PrimaryWindow", "Random"))
        self.comboBox_2.setItemText(2, _translate("PrimaryWindow", "Quadrada"))
        self.comboBox_2.setItemText(3, _translate("PrimaryWindow", "Serra"))
        self.comboBox_2.setItemText(4, _translate("PrimaryWindow", "Degrau"))
        self.pushButton.setText(_translate("PrimaryWindow", "Ok"))
