# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StepWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StepWindow(object):
    def setupUi(self, StepWindow):
        StepWindow.setObjectName("StepWindow")
        StepWindow.resize(668, 344)
        StepWindow.setMinimumSize(QtCore.QSize(668, 344))
        StepWindow.setMaximumSize(QtCore.QSize(668, 344))
        self.centralwidget = QtWidgets.QWidget(StepWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_green = QtWidgets.QFrame(self.centralwidget)
        self.frame_green.setGeometry(QtCore.QRect(-10, 0, 131, 341))
        self.frame_green.setStyleSheet("background-color: rgb(156, 204, 152);")
        self.frame_green.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_green.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_green.setObjectName("frame_green")
        self.frame_white = QtWidgets.QFrame(self.centralwidget)
        self.frame_white.setGeometry(QtCore.QRect(119, -1, 551, 351))
        self.frame_white.setMinimumSize(QtCore.QSize(551, 351))
        self.frame_white.setMaximumSize(QtCore.QSize(551, 351))
        self.frame_white.setStyleSheet("background-color: rgb(250, 245, 245);")
        self.frame_white.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_white.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_white.setObjectName("frame_white")
        self.label_title = QtWidgets.QLabel(self.frame_white)
        self.label_title.setGeometry(QtCore.QRect(110, 50, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_white)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 140, 231, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(19, 5, 23, 0)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_amplitude = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_amplitude.setFont(font)
        self.label_amplitude.setObjectName("label_amplitude")
        self.horizontalLayout.addWidget(self.label_amplitude)
        self.lineEdit_amplitude = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_amplitude.setToolTip("")
        self.lineEdit_amplitude.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"background: white;\n"
"};")
        self.lineEdit_amplitude.setText("")
        self.lineEdit_amplitude.setPlaceholderText("")
        self.lineEdit_amplitude.setObjectName("lineEdit_amplitude")
        self.horizontalLayout.addWidget(self.lineEdit_amplitude)
        self.step_button = QtWidgets.QPushButton(self.frame_white)
        self.step_button.setGeometry(QtCore.QRect(200, 270, 111, 41))
        self.step_button.setStyleSheet("QPushButton{\n"
"border: 2px solid black;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton:pressed {\n"
"    background-color: gray;\n"
"    color:white;\n"
"}")
        self.step_button.setObjectName("step_button")
        StepWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StepWindow)
        QtCore.QMetaObject.connectSlotsByName(StepWindow)

    def retranslateUi(self, StepWindow):
        _translate = QtCore.QCoreApplication.translate
        StepWindow.setWindowTitle(_translate("StepWindow", "MainWindow"))
        self.label_title.setText(_translate("StepWindow", "Configurações Degrau"))
        self.label_amplitude.setText(_translate("StepWindow", "Amplitude"))
        self.step_button.setText(_translate("StepWindow", "Gerar Sinal"))
