# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowGraphic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from graphics.mplwidget import MplWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("")
        MainWindow.resize(1011, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_green = QtWidgets.QFrame(self.centralwidget)
        self.frame_green.setGeometry(QtCore.QRect(-1, -1, 41, 611))
        self.frame_green.setStyleSheet("background-color: rgb(156, 204, 152);")
        self.frame_green.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_green.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_green.setObjectName("frame_green")
        self.frame_white = QtWidgets.QFrame(self.centralwidget)
        self.frame_white.setGeometry(QtCore.QRect(39, -1, 981, 611))
        self.frame_white.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame_white.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_white.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_white.setObjectName("frame_white")
        self.MlpWidget = MplWidget(self.frame_white)
        self.MlpWidget.setGeometry(QtCore.QRect(60, 60, 871, 501))
        self.MlpWidget.setStyleSheet("QWidget{\n"
"        border: 2px solid gray;\n"
"};")
        self.MlpWidget.setObjectName("MlpWidget")
        self.frame_white.raise_()
        self.frame_green.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
